GET https://firestore.googleapis.com/v1/projects/pokoy-1bf7f/databases/(default)/documents/days/03jU3DyrdUwVrF3C6Xrm HTTP/1.1
Authorization: Bearer ya29.a0ARrdaM_aG7L4fAMFiK8Zs2IyeCTTue5PYKzISMg5bpOgvv8apfwClTAXjxNPD9nJQlmTzNcqRd5KrsL6oo3Ic9dPjWDUddqoITxdduImTTDyNvJNmREVe-YXdNstJlW37vD8uHNWYNub_1ADn-6FabL9uUYk1hUrnLncRd30KEQvtPdf6yIkfxdYKnrYlYIhwXXH8R1t0zhDpxqVYK4Umog9wNfg0cWPqViPniIN2btpwBpvG38xlL-gxfmaeKKVXQ9QKw